AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Email SQS queue and lambda

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      bucket: emails-service-storage
      domain: dbowland.com
      errorTopic: arn:aws:sns:us-east-1:494887012091:error-topic
      logStreamFunction: log-subscriber
      project: emails-queue-service
    test:
      bucket: emails-service-storage-test
      domain: bowland.link
      errorTopic: arn:aws:sns:us-east-1:494887012091:error-topic-test
      logStreamFunction: log-subscriber-test
      project: emails-queue-service-test

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600 # 14 days
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: 'created-by'
          Value: 'emails-queue-service'
        - Key: 'created-for'
          Value: 'emails'
        - Key: 'environment'
          Value: !Ref Environment
      VisibilityTimeout: 60

  SQSPayloadProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Description: Processes queued messages to send emails.
      Environment:
        Variables:
          DOMAIN: !FindInMap [EnvironmentMap, !Ref Environment, domain]
          EMAIL_BUCKET: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
          EMAIL_REGION: us-east-1
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            BatchSize: 7
            Queue: !GetAtt SimpleQueue.Arn
      Handler: src/handlers/sqs-payload-processor.sqsPayloadProcessorHandler
      MemorySize: 128
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Grant access to S3 bucket
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
        # Grant access to SES identity
        - SESCrudPolicy:
            IdentityName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
        # Grant access to SQS queue
        - SQSPollerPolicy:
            QueueName: !GetAtt SimpleQueue.QueueName
      Runtime: nodejs22.x
      Tags:
        'created-by': 'emails-queue-service'
        'created-for': 'emails'
        'environment': !Ref Environment
      Timeout: 60
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - src/handlers/sqs-payload-processor.ts

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [SQSPayloadProcessor]
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSPayloadProcessor}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'emails-queue-service'
        - Key: 'created-for'
          Value: 'emails'
        - Key: 'environment'
          Value: !Ref Environment

  LambdaLogGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref LambdaLogGroup
